### ISSUE TITLE
Slides of Mitos aren't working

### ISSUE THREAD

**Issue by miglsoares** [juuh42dias/transervicos#12]
# Context
Today the Mitos session is broken slideshow. It doesn't work when clicking the buttons to move from one slide to another. This means not reading the other myths involving transgender people.

# Screenshots
<img width="797" alt="Screen Shot 2019-10-05 at 22 46 29" src="https://user-images.githubusercontent.com/20358128/66263011-0a0ff380-e7c2-11e9-8fba-ca0cce193e84.png">

# Acceptance Criteria
- [ ] Slides from Mitos section are working
- [ ] Add max-height to `.mito`

**Comment by marceloperini** [comment]
@juuh42dias @miglsoares I can open a PR to fix this

**Comment by miglsoares** [comment]
go head, @marceloperini !

**Comment by juuh42dias** [comment]
> This is already solved @miglsoares @juuh42dias ?

yeap, I forgot close this PR :woman_facepalming:
