### ISSUE TITLE
Padronizar o idioma que usamos no projeto

### ISSUE THREAD

**Issue by Auralcat** [juuh42dias/transervicos#24]
# Motivação
Resumindo, eu tô perdida com as linguagens e misturando en_US com pt_BR :S

O que vcs acham? Em uma discussão mais cedo hoje, optamos por manter a comunicação em português. Pra isso, seria bom alterar os templates de issues que colocamos aqui, e até mesmo incluir um template pros PRs.

**Comment by juuh42dias** [comment]
Como o foco do projeto é o público Br, eu sugiro que as discussões se mantenham em pt-BR mas commits e código seguem os padrões em en-US/UK/XX mesmo.

**Comment by Auralcat** [comment]
Como fazemos com os PRs e issues? Ficam em português mesmo?

**Comment by juuh42dias** [comment]
Yep, issues e PR's em pt-BR

**Comment by Auralcat** [comment]
Posso atualizar os templates então :D

**Comment by juuh42dias** [comment]
go ahead hehehe digo, vá em frente
